{
 "title": "Wifi",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(wifi_signal_db{job=\"wifi_exporter\"},instance)"
    }
   },
   {
    "name": "interface",
    "query": {
     "query": "label_values(wifi_signal_db{job=\"wifi_exporter\",instance=~\"$instance\"},interface)"
    }
   },
   {
    "name": "frequency_band",
    "query": {
     "query": "label_values(wifi_signal_db{job=\"wifi_exporter\",instance=~\"$instance\"},frequency_band)"
    }
   },
   {
    "name": "channel",
    "query": {
     "query": "label_values(wifi_signal_db{job=\"wifi_exporter\",instance=~\"$instance\",frequency_band=~\"$frequency_band\"},channel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "BSS count by Channel",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count by (channel,frequency_band)(wifi_signal_db{\n    job=\"wifi_exporter\",\n    instance=~\"$instance\",\n    interface=~\"$interface\",\n    frequency_band=~\"$frequency_band\",\n    channel=~\"$channel\",\n})\n# 2.4GHz\nor (label_replace(label_replace(vector(0), \"channel\", \"1\", \"\", \"\"), \"frequency_band\", \"2.4GHz\", \"\", \"\") and label_replace(label_replace(vector(0), \"channel\", \"1\", \"\", \"\"), \"frequency_band\", \"$frequency_band\", \"\", \"\") )\nor (label_replace(label_replace(vector(0), \"channel\", \"2\", \"\", \"\"), \"frequency_band\", \"2.4GHz\", \"\", \"\") and label_replace(label_replace(vector(0), \"channel\", \"2\", \"\", \"\"), \"frequency_band\", \"$frequency_band\", \"\", \"\") )\nor (label_replace(label_replace(vector(0), \"channel\", \"3\", \"\", \"\"), \"frequency_band\", \"2.4GHz\", \"\", \"\") and label_replace(label_replace(vector(0), \"channel\", \"3\", \"\", \"\"), \"frequency_band\", \"$frequency_band\", \"\", \"\") )\nor (label_replace(label_replace(vector(0), \"channel\", \"4\", \"\", \"\"), \"frequency_band\", \"2.4GHz\", \"\", \"\") and label_replace(label_replace(vector(0), \"channel\", \"4\", \"\", \"\"), \"frequency_band\", \"$frequency_band\", \"\", \"\") )\nor (label_replace(label_replace(vector(0), \"channel\", \"5\", \"\", \"\"), \"frequency_band\", \"2.4GHz\", \"\", \"\") and label_replace(label_replace(vector(0), \"channel\", \"5\", \"\", \"\"), \"frequency_band\", \"$frequency_band\", \"\", \"\") )\nor (label_replace(label_replace(vector(0), \"channel\", \"6\", \"\", \"\"), \"frequency_band\", \"2.4GHz\", \"\", \"\") and label_replace(label_replace(vector(0), \"channel\", \"6\", \"\", \"\"), \"frequency_band\", \"$frequency_band\", \"\", \"\") )\nor (label_replace(label_replace(vector(0), \"channel\", \"7\", \"\", \"\"), \"frequency_band\", \"2.4GHz\", \"\", \"\") and label_replace(label_replace(vector(0), \"channel\", \"7\", \"\", \"\"), \"frequency_band\", \"$frequency_band\", \"\", \"\") )\nor (label_replace(label_replace(vector(0), \"channel\", \"8\", \"\", \"\"), \"frequency_band\", \"2.4GHz\", \"\", \"\") and label_replace(label_replace(vector(0), \"channel\", \"8\", \"\", \"\"), \"frequency_band\", \"$frequency_band\", \"\", \"\") )\nor (label_replace(label_replace(vector(0), \"channel\", \"9\", \"\", \"\"), \"frequency_band\", \"2.4GHz\", \"\", \"\") and label_replace(label_replace(vector(0), \"channel\", \"9\", \"\", \"\"), \"frequency_band\", \"$frequency_band\", \"\", \"\") )\nor (label_replace(label_replace(vector(0), \"channel\", \"10\", \"\", \"\"), \"frequency_band\", \"2.4GHz\", \"\", \"\") and label_replace(label_replace(vector(0), \"channel\", \"10\", \"\", \"\"), \"frequency_band\", \"$frequency_band\", \"\", \"\") )\nor (label_replace(label_replace(vector(0), \"channel\", \"11\", \"\", \"\"), \"frequency_band\", \"2.4GHz\", \"\", \"\") and label_replace(label_replace(vector(0), \"channel\", \"11\", \"\", \"\"), \"frequency_band\", \"$frequency_band\", \"\", \"\") )\nor (label_replace(label_replace(vector(0), \"channel\", \"12\", \"\", \"\"), \"frequency_band\", \"2.4GHz\", \"\", \"\") and label_replace(label_replace(vector(0), \"channel\", \"12\", \"\", \"\"), \"frequency_band\", \"$frequency_band\", \"\", \"\") )\nor (label_replace(label_replace(vector(0), \"channel\", \"13\", \"\", \"\"), \"frequency_band\", \"2.4GHz\", \"\", \"\") and label_replace(label_replace(vector(0), \"channel\", \"13\", \"\", \"\"), \"frequency_band\", \"$frequency_band\", \"\", \"\") )\n# 5GHz\nor (label_replace(label_replace(vector(0), \"channel\", \"36\", \"\", \"\"), \"frequency_band\", \"5GHz\", \"\", \"\") and label_replace(label_replace(vector(0), \"channel\", \"36\", \"\", \"\"), \"frequency_band\", \"$frequency_band\", \"\", \"\") )\nor (label_replace(label_replace(vector(0), \"channel\", \"40\", \"\", \"\"), \"frequency_band\", \"5GHz\", \"\", \"\") and label_replace(label_replace(vector(0), \"channel\", \"40\", \"\", \"\"), \"frequency_band\", \"$frequency_band\", \"\", \"\") )\nor (label_replace(label_replace(vector(0), \"channel\", \"44\", \"\", \"\"), \"frequency_band\", \"5GHz\", \"\", \"\") and label_replace(label_replace(vector(0), \"channel\", \"44\", \"\", \"\"), \"frequency_band\", \"$frequency_band\", \"\", \"\") )\nor (label_replace(label_replace(vector(0), \"channel\", \"48\", \"\", \"\"), \"frequency_band\", \"5GHz\", \"\", \"\") and label_replace(label_replace(vector(0), \"channel\", \"48\", \"\", \"\"), \"frequency_band\", \"$frequency_band\", \"\", \"\") )\nor (label_replace(label_replace(vector(0), \"channel\", \"52\", \"\", \"\"), \"frequency_band\", \"5GHz\", \"\", \"\") and label_replace(label_replace(vector(0), \"channel\", \"52\", \"\", \"\"), \"frequency_band\", \"$frequency_band\", \"\", \"\") )\nor (label_replace(label_replace(vector(0), \"channel\", \"56\", \"\", \"\"), \"frequency_band\", \"5GHz\", \"\", \"\") and label_replace(label_replace(vector(0), \"channel\", \"56\", \"\", \"\"), \"frequency_band\", \"$frequency_band\", \"\", \"\") )\nor (label_replace(label_replace(vector(0), \"channel\", \"60\", \"\", \"\"), \"frequency_band\", \"5GHz\", \"\", \"\") and label_replace(label_replace(vector(0), \"channel\", \"60\", \"\", \"\"), \"frequency_band\", \"$frequency_band\", \"\", \"\") )\nor (label_replace(label_replace(vector(0), \"channel\", \"64\", \"\", \"\"), \"frequency_band\", \"5GHz\", \"\", \"\") and label_replace(label_replace(vector(0), \"channel\", \"64\", \"\", \"\"), \"frequency_band\", \"$frequency_band\", \"\", \"\") )\nor (label_replace(label_replace(vector(0), \"channel\", \"100\", \"\", \"\"), \"frequency_band\", \"5GHz\", \"\", \"\") and label_replace(label_replace(vector(0), \"channel\", \"100\", \"\", \"\"), \"frequency_band\", \"$frequency_band\", \"\", \"\") )\nor (label_replace(label_replace(vector(0), \"channel\", \"104\", \"\", \"\"), \"frequency_band\", \"5GHz\", \"\", \"\") and label_replace(label_replace(vector(0), \"channel\", \"104\", \"\", \"\"), \"frequency_band\", \"$frequency_band\", \"\", \"\") )\nor (label_replace(label_replace(vector(0), \"channel\", \"108\", \"\", \"\"), \"frequency_band\", \"5GHz\", \"\", \"\") and label_replace(label_replace(vector(0), \"channel\", \"108\", \"\", \"\"), \"frequency_band\", \"$frequency_band\", \"\", \"\") )\nor (label_replace(label_replace(vector(0), \"channel\", \"112\", \"\", \"\"), \"frequency_band\", \"5GHz\", \"\", \"\") and label_replace(label_replace(vector(0), \"channel\", \"112\", \"\", \"\"), \"frequency_band\", \"$frequency_band\", \"\", \"\") )\nor (label_replace(label_replace(vector(0), \"channel\", \"116\", \"\", \"\"), \"frequency_band\", \"5GHz\", \"\", \"\") and label_replace(label_replace(vector(0), \"channel\", \"116\", \"\", \"\"), \"frequency_band\", \"$frequency_band\", \"\", \"\") )\nor (label_replace(label_replace(vector(0), \"channel\", \"120\", \"\", \"\"), \"frequency_band\", \"5GHz\", \"\", \"\") and label_replace(label_replace(vector(0), \"channel\", \"120\", \"\", \"\"), \"frequency_band\", \"$frequency_band\", \"\", \"\") )\nor (label_replace(label_replace(vector(0), \"channel\", \"124\", \"\", \"\"), \"frequency_band\", \"5GHz\", \"\", \"\") and label_replace(label_replace(vector(0), \"channel\", \"124\", \"\", \"\"), \"frequency_band\", \"$frequency_band\", \"\", \"\") )\nor (label_replace(label_replace(vector(0), \"channel\", \"128\", \"\", \"\"), \"frequency_band\", \"5GHz\", \"\", \"\") and label_replace(label_replace(vector(0), \"channel\", \"128\", \"\", \"\"), \"frequency_band\", \"$frequency_band\", \"\", \"\") )",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  {
   "title": "BSS Channel",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by (BSSID,SSID)(wifi_channel{\n    job=\"wifi_exporter\",\n    instance=~\"$instance\",\n    interface=~\"$interface\",\n    frequency_band=~\"$frequency_band\",\n})",
     "legendFormat": "{{SSID}} {{BSSID}}"
    }
   ]
  },
  {
   "title": "Signal Strength by BSS",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by (BSSID,SSID)(wifi_signal_db{\n    job=\"wifi_exporter\",\n    instance=~\"$instance\",\n    interface=~\"$interface\",\n    frequency_band=~\"$frequency_band\",\n    channel=~\"$channel\",\n})",
     "legendFormat": "{{SSID}} {{BSSID}}"
    }
   ]
  },
  {
   "title": "Signal Strength by BSS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "sum by (BSSID,SSID)(wifi_signal_db{\n    job=\"wifi_exporter\",\n    instance=~\"$instance\",\n    interface=~\"$interface\",\n    frequency_band=~\"$frequency_band\",\n    channel=~\"$channel\",\n})",
     "legendFormat": "{{SSID}} {{BSSID}}"
    }
   ]
  },
  {
   "title": "Wifi Scan Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "wifi_scan_duration_seconds{\n    job=\"wifi_exporter\",\n    instance=~\"$instance\",\n}",
     "legendFormat": "{{SSID}} {{BSSID}}"
    }
   ]
  },
  {
   "title": "Up",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "up{\n    job=\"wifi_exporter\",\n    instance=~\"$instance\",\n}",
     "legendFormat": "{{SSID}} {{BSSID}}"
    }
   ]
  }
 ]
}